const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1092,height:1021},acceptDownloads:true});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const owned=new Set(); page.on('response', async response=>{if(response.url().endsWith('/api/library/items') && response.request().method()==='POST' && response.ok()) {owned.add((await response.json()).id);}}); const title='Persistence acceptance '+Date.now();
 await page.goto('http://127.0.0.1:8765/?view=copilot');
 await page.locator('#save-status').filter({hasText:/Ready to save|Saved conversation restored/}).waitFor();
 await page.getByRole('button',{name:'New chat',exact:true}).click();
 await page.locator('#chat-title').fill(title);
 await page.getByRole('combobox',{name:'Answer style',exact:true}).selectOption('evidence');
 await page.getByRole('textbox',{name:'Ask the course archive',exact:true}).fill('What is option gamma?');
 await page.getByRole('button',{name:'Ask locally',exact:true}).click();
 await page.getByRole('button',{name:'Save answer',exact:true}).waitFor({timeout:30000});
 await page.locator('#save-status').filter({hasText:'Saved on this Mac'}).waitFor();
 const savedURL=page.url();
 await page.reload();
 await page.getByRole('button',{name:'Save answer',exact:true}).waitFor();
 await page.getByRole('button',{name:'Save answer',exact:true}).click();
 await page.getByRole('button',{name:'New chat',exact:true}).click();
 assert.equal(await page.locator('.conversation-turn').count(),0);
 await page.getByRole('button',{name:'Saved',exact:true}).click();
 await page.locator('.saved-card').filter({hasText:title}).getByRole('button',{name:'Open',exact:true}).click();
 await page.getByRole('button',{name:'Save answer',exact:true}).waitFor();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export chat',exact:true}).click();
 const download=await downloadPromise;assert.equal(download.suggestedFilename(),'mafn-conversation.json');
 await page.locator('.copilot-citation').first().click();
 await page.locator('#save-source').waitFor({state:'visible'});await page.locator('#save-source').click();
 await page.getByRole('button',{name:'Saved',exact:true}).click();
 await page.locator('.saved-group').filter({hasText:'Saved passages'}).locator('.saved-card').first().waitFor();
 await page.screenshot({path:'.rag/viewer/qa/saved-1092.png',fullPage:true});
 await context.close();
 const fresh=await browser.newContext();const reopened=await fresh.newPage();await reopened.goto(savedURL);
 await reopened.getByRole('button',{name:'Save answer',exact:true}).waitFor();
 assert.equal(await reopened.locator('.conversation-turn').count(),1);
 const after=(await(await fresh.request.get('http://127.0.0.1:8765/api/library')).json()).items;
 for(const item of after.filter(i=>owned.has(i.id))) await fresh.request.post('http://127.0.0.1:8765/api/library/delete',{data:{item_id:item.id,revision:item.revision}});
 assert.deepEqual(errors,[]);console.log('Chat reload, fresh browser context, new chat, history, answer/passages and export passed; test records deleted.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
